version: 1
project:
    spec: 1
    name: NFRO1
    todo:
        -
            name: 'SPM'
            pieces:
                -
                    name:   'pre'
                    type:   'preprocess'
                    stages: ['slicetime', 'realign-er','normalize-er', 'smooth']
                -
                    name:   'art_rej'
                    type:   'art'
                    stages: ['art']
                -
                    name:   'post-AC'
                    type:   'stats'
                    art:    true
                    stages: ['model', 'estimate', 'contrast_manager', 'results']
                -
                    name:   'post-RI'
                    type:   'stats'
                    art:    true
                    stages: ['model', 'estimate', 'contrast_manager', 'results']
                -
                    name:   'post-WNW'
                    type:   'stats'
                    art:    true
                    stages: ['model', 'estimate', 'contrast_manager', 'results']

    paradigms:
        -
            name:   Pre
            n_runs: 2
            n_volumes: 94
            output_directory: /Users/scottburns/Analysis/NFRO1/Pre/
            data_toplevel: /Volumes/Data/NFRO1/Pre/
            run_directory:
                - M1
                - M2
            images:
                - SWR1.nii
                - SWR2.nii
            SPM:
                session:
                    multiple_condition_mat:
                        post-AC:
                            - /Users/scottburns/Analysis/NFRO1/Pre/mult_cond/post-AC/AC-M1.mat
                            - /Users/scottburns/Analysis/NFRO1/Pre/mult_cond/post-AC/AC-M2.mat
                        post-RI:
                            - /Users/scottburns/Analysis/NFRO1/Pre/mult_cond/post-RI/RI-M1.mat
                            - /Users/scottburns/Analysis/NFRO1/Pre/mult_cond/post-RI/RI-M2.mat
                        post-WNW:
                            - /Users/scottburns/Analysis/NFRO1/Pre/mult_cond/post-WNW/WNW-M1.mat
                            - /Users/scottburns/Analysis/NFRO1/Pre/mult_cond/post-WNW/WNW-M2.mat                        
            contrasts:
                post-AC:
                    -
                        name:   Meaningful_Sent
                        vector: '1 0 0 0'
                        replication: replsc
                    -
                        name:   Syntactic_Sent
                        vector: '0 1 0 0'
                        replication: replsc
                    -
                        name:   Semantic_Sent
                        vector: '0 0 1 0'
                        replication: replsc
                    -
                        name:   Words
                        vector: '0 0 0 1'
                        replication: replsc                    
                post-RI:
                    -
                        name:   TrueSent-3
                        vector: '1 0 0 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   NonSent-3
                        vector: '0 1 0 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   Words-3
                        vector: '0 0 1 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   TrueSent-5
                        vector: '0 0 1 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   NonSent-5
                        vector: '0 0 0 1 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   Words-5
                        vector: '0 0 0 0 1 0 0 0 0'
                        replication: replsc
                    -
                        name:   TrueSent-7
                        vector: '0 0 0 0 0 1 0 0 0'
                        replication: replsc
                    -
                        name:   NonSent-7
                        vector: '0 0 0 0 0 0 0 1 0'
                        replication: replsc
                    -
                        name:   Words-7
                        vector: '0 0 0 0 0 0 0 0 1'
                        replication: replsc
                post-WNW:
                    -
                        name:
                        vector:
                        replication:

        -
            name:   Post
            n_runs: 2
            n_volumes: 94
            output_directory: /Users/scottburns/Analysis/NFRO1/Post/
            data_toplevel: /Volumes/Data/NFRO1/Post/
            run_directory:
                - M1
                - M2
            images:
                - SWR1.nii
                - SWR2.nii
            SPM:
                session:
                    multiple_condition_mat:
                        post-AC:
                            - /Users/scottburns/Analysis/NFRO1/Post/mult_cond/post-AC/AC-M1.mat
                            - /Users/scottburns/Analysis/NFRO1/Post/mult_cond/post-AC/AC-M2.mat
                        post-RI:
                            - /Users/scottburns/Analysis/NFRO1/Post/mult_cond/post-RI/RI-M1.mat
                            - /Users/scottburns/Analysis/NFRO1/Post/mult_cond/post-RI/RI-M2.mat
                        post-WNW:
                            - /Users/scottburns/Analysis/NFRO1/Post/mult_cond/post-WNW/WNW-M1.mat
                            - /Users/scottburns/Analysis/NFRO1/Post/mult_cond/post-WNW/WNW-M2.mat                        
