subjects:
    -
        id: 2005
        grp: CNT
    -
    	id: 2010
    	grp: CNT
    -
    	id: 2011
    	grp: CNT
    -
    	id: 2012
    	grp: CNT
    -
    	id: 2013
    	grp: CNT
    -
    	id: 2014
    	grp: CNT
    -
    	id: 2015
    	grp: CNT
    -
    	id: 2016
    	grp: CNT
    -
    	id: 2017
    	grp: CNT
    -
    	id: 2018
    	grp: CNT
    -
    	id: 2019
    	grp: CNT
    -
    	id: 2027
    	grp: CNT
    -
    	id: 2028
    	grp: CNT
    -
    	id: 2028
    	grp: CNT
    -
    	id: 2029
    	grp: CNT
    -
    	id: 2030
    	grp: CNT
    -
    	id: 2031
    	grp: CNT
    -
    	id: 2500
    	grp: CNT
    -
    	id: 2505
    	grp: CNT
    -
    	id: 2501
    	grp: CNT
    -
    	id: 2506
    	grp: CNT
    -
    	id: 3017
    	grp: RD
    -
    	id: 3024
    	grp: RD
    -
    	id: 3017
    	grp: RD
    -
        id: 2024
        grp: RD
    -
        id: 3024
        grp: RD
    -
        id: 3026
        grp: RD
    -
        id: 3500
        grp: RD
    -
        id: 3514
        grp: RD
    -
        id: 3517
        grp: RD
    -
        id: 3521
        grp: RD
    -
        id: 3522
        grp: RD
    -
        id: 3523
        grp: RD
    -
        id: 3001
        grp: RD-WL
    -
        id: 3004
        grp: RD-WL
    -
        id: 3010
        grp: RD-WL
    -
        id: 3012
        grp: RD-WL
    -
        id: 3013
        grp: RD-WL
    -
        id: 3016
        grp: RD-WL
    -
        id: 3020
        grp: RD-WL
    -
        id: 3025
        grp: RD-WL
    -
        id: 3513
        grp: RD-WL
    -
        id: 3511
        grp: RD-WL
