version: 1
matlab_path: /Users/scottburns/Applications/MATLAB_R2011b.app/bin/matlab
SPM:
    spec:   1
    slicetime:
        batch_n:    1
        images:     'gen'
        nslices:    40
        tr:         2.2
        ta:         2.145
        so:         "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40"
        ref:        20
        prefix:        a
    realign-er:
        batch_n:            2
        images:             'gen'
        quality:            1.0
        separation:         4
        smoothing:          6
        num_passes:         0
        e_interpolation:    2
        e_wrap:             '0 0 0'
        weight:             ''
        which:              '2 1'
        r_interpolation:    4
        r_wrap:             '0 0 0'
        mask:               1
        prefix:             'r'
    normalize-er:
        batch_n:    3
        source:     'gen'
        weight_src: ''
        images:     'gen'
        template:   '/Applications/spm8/templates/EPI.nii,1'
        template_weight:    ''
        source_smooth:  6
        template_smooth:    0
        reg_type:   mni
        freq_cutoff:    25
        iterations:     16
        regularization: 1
        preserve:       0
        bounding_box:   "-78 -112 -50; 78 76 85"
        voxel_size:     "2 2 2"
        interpolation:  2
        wrap:       '0 0 0'
        prefix:     'w'
    smooth:
        batch_n:    4
        images:     'gen'
        fwhm:       '8 8 8'
        datatype:   0
        implicit:   0
        prefix:     's'
    model:
        batch_n:    1
        directory:  'gen'
        timing_units:   'scans'
        TR: 2.2
        microtime_resolution:   16
        microtime_onset:    1
        session:    'gen'
        hrf_derivatives:    '0 0'
        volterra_interactions:  1
        global_normalization:   'None'
        explicit_mask:  ''
        serial_correlations:    'AR(1)'
    session:
        batch_n:    1
        session_n:  'gen'
        images:     'gen'
        multiple_condition_mat: 'gen'
        multiple_regression_file:   'gen'
        hpf:        128
    estimate:
        batch_n:    2
        spm_mat_file:   'gen'
    contrast_manager:
        batch_n:    3
        spm_mat_file:   'gen'
        contrast:   'gen'
        delete:     1
    contrast:
        batch_n:    3
    results:
        batch_n:    4
        spm_mat_file:   'gen'
        titlestr:   ''
        contrasts:  Inf
        thresh_desc:    'none'
        threshold:  0.001

