version: 1
subjects:
    -
        'id': '01'
    -
        'id': '02'
    -
        'id': '03'
    -
        'id': '05'
    -
        'id': '07'
    -
        'id': '08'
    -
        'id': '09'
    -
        'id': '10'
    -
        'id': '12'
    -
        'id': '13'
    -
        'id': '14'
    -
        'id': '15'
    -
        'id': '16'
    -
        'id': '17'
    -
        'id': '18'
    -
        'id': '19'
    -
        'id': '20'
    -
        'id': '21'
    -
        'id': '22'
    -
        'id': '23'
    -
        'id': '24'
    -
        'id': '25'
    -
        'id': '26'
    -
        'id': '27'
    -
        'id': '28'
    -
        'id': '29'
    -
        'id': '30'
