version: 1
project:
    spec: 1
    name: LERDLMS_SRT
    todo:
        -
            name: 'SPM'
            pieces:
                -
                    name:   'pre'
                    type:   'preprocess'
                    stages: ['slicetime', 'realign-er','normalize-er', 'smooth']
                -
                    name:   'art_rej'
                    type:   'art'
                    stages: ['art']
                -
                    name:   'first-level'
                    type:   'stats'
                    art:    true
                    stages: ['model', 'estimate', 'contrast_manager', 'results']
    paradigms:
        -
            name:   SRT
            n_runs: 2
            n_volumes: 142
            output_directory: /scratch/burnsss1/New_Server/LERDLMS/MR_Processed/
            data_toplevel: /scratch/burnsss1/New_Server/LERDLMS/MR_Processed/
            run_directory:
                - M1
                - M2
            images:
                - SRT1.nii
                - SRT2.nii
            SPM:
                slicetime:
                    so: '1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40'
                session:
                    multiple_condition_mat:
                        first-level:
                            - /scratch/burnsss1/New_Server/LERDLMS/timing/SRT/SRT_ListA_M1.mat
                            - /scratch/burnsss1/New_Server/LERDLMS/timing/SRT/SRT_ListA_M2.mat
            contrasts:
                -
                    name: 'Implicit - Baseline'
                    vector: '1 0'
                    replication: 'replsc'
                -
                    name: 'Random - Baseline'
                    vector: '0 1'
                    replication: 'replsc'
                -
                    name: 'Implicit - Random'
                    vector: '1 -1'
                    replication: 'replsc'
                -
                    name: 'Random - Implicit'
                    vector: '-1 1'
                    replication: 'replsc'
