version: 1
project:
    spec: 1
    name: NF-REP
    todo:
        -
            name: 'SPM'
            pieces:
                -
                    name:   'pre'
                    type:   'preprocess'
                    stages: ['slicetime', 'realign-er','normalize-er', 'smooth']
                -
                    name:   'art_rej'
                    type:   'art'
                    stages: ['art']
                -
                    name:   'first-level'
                    type:   'stats'
                    art:    true
                    stages: ['model', 'estimate', 'contrast_manager', 'results']
    paradigms:
        -
            name:   REP
            n_runs: 3
            n_volumes: 135
            output_directory: /scratch/burnsss1/New_Server/NF/MR_Processed/
            data_toplevel: /scratch/burnsss1/New_Server/NF/MR_Processed/
            run_directory:
                - M1
                - M2
                - M2
            images:
                - Rep1.nii
                - Rep2.nii
                - Rep3.nii
            SPM:
                session:
                    multiple_condition_mat:
                        first-level:
                            - /scratch/burnsss1/New_Server/NF/Other/task_timing/REP/REP_M1.mat
                            - /scratch/burnsss1/New_Server/NF/Other/task_timing/REP/REP_M2.mat
                            - /scratch/burnsss1/New_Server/NF/Other/task_timing/REP/REP_M3.mat
            contrasts:
                first-level:
                    -
                        name:   Words-Baseline
                        vector: '0 1'
                        replication: replsc
                    -
                        name:   Nonwords-Baseline
                        vector: '1 0'
                        replication: replsc
                    -
                        name:   Words-Nonwords
                        vector: '-1 1'
                        replication: replsc
                    -
                        name:   Nonwords-Words
                        vector: '-1 1'
                        replication: replsc


