version: 1
lists:
    PassagesV2-CP:
        SPM:
            session:
                multiple_condition_mat:
                    '1':
                        - /scratch/burnsss1/New_Server/RCV/timing/PassagesV2/PassagesV2-CP_ListA_M1.mat
                        - /scratch/burnsss1/New_Server/RCV/timing/PassagesV2/PassagesV2-CP_ListA_M2.mat
                        - /scratch/burnsss1/New_Server/RCV/timing/PassagesV2/PassagesV2-CP_ListA_M3.mat
                        - /scratch/burnsss1/New_Server/RCV/timing/PassagesV2/PassagesV2-CP_ListA_M4.mat
                    '2':
                        - /scratch/burnsss1/New_Server/RCV/timing/PassagesV2/PassagesV2-CP_ListB_M1.mat
                        - /scratch/burnsss1/New_Server/RCV/timing/PassagesV2/PassagesV2-CP_ListB_M2.mat
                        - /scratch/burnsss1/New_Server/RCV/timing/PassagesV2/PassagesV2-CP_ListB_M3.mat
                        - /scratch/burnsss1/New_Server/RCV/timing/PassagesV2/PassagesV2-CP_ListB_M4.mat
project:
    spec: 1
    name: RCV_PassagesV2-CP
    todo:
        -
            name: 'SPM'
            pieces:
                -
                    name:   'pre'
                    type:   'preprocess'
                    stages: ['slicetime', 'realign-er','normalize-er', 'smooth']
                -
                    name:   'art_rej'
                    type:   'art'
                    stages: ['art']
                -
                    name:   'first-level'
                    type:   'stats'
                    art:    true
                    stages: ['model', 'estimate', 'contrast_manager', 'results']
    paradigms:
        -
            name:   PassagesV2-CP
            n_runs: 4
            n_volumes: 200
            output_directory: /scratch/burnsss1/New_Server/RCV/MR_Processed/
            data_toplevel: /scratch/burnsss1/New_Server/RCV/MR_Processed/
            run_directory:
                - M1
                - M2
                - M3
                - M4
            images:
                - Pass1.nii
                - Pass2.nii
                - Pass3.nii
                - Pass4.nii
            SPM:
                slicetime:
                    so: '1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40'
            contrasts:
                -
                    name: 'Central - Baseline'
                    vector: '1 0 0 0'
                    replication: 'replsc'
                -
                    name: 'Peripheral - Baseline'
                    vector: '0 1 0 0'
                    replication: 'replsc'
                -
                    name: 'Words - Baseline'
                    vector: '0 0 1 0'
                    replication: 'replsc'
                -
                    name: 'Central&Peripheral'
                    vector: '.5 .5 0 0'
                    replication: 'replsc'
                -
                    name: 'Central&Peripheral - Words'
                    vector: '.5 .5 -1 0'
                    replication: 'replsc'
                -
                    name: 'Words - Central&Peripheral'
                    vector: '-.5 -.5 1 0'
                    replication: 'replsc'
                -
                    name: 'Central - Words'
                    vector: '1 0 -1 0'
                    replication: 'replsc'
                -
                    name: 'Words - Central'
                    vector: '-1 0 1 0'
                    replication: 'replsc'
                -
                    name: 'Peripheral - Words'
                    vector: '0 1 -1 0'
                    replication: 'replsc'
                -
                    name: 'Words - Peripheral'
                    vector: '0 -1 1 0'
                    replication: 'replsc'
