version: 1
project:
    spec: 1
    name: LDRC_KKI
    todo:
        -
            name: 'SPM'
            pieces:
                -
                    name:   'pre'
                    type:   'preprocess'
                    stages: ['slicetime', 'realign-er','normalize-er', 'smooth']
                -
                    name:   'art_rej'
                    type:   'art'
                    stages: ['art']
                -
                    name:   'post-model1'
                    type:   'stats'
                    art:    true
                    stages: ['model', 'estimate', 'contrast_manager', 'results']
                -
                    name:   'post-model2'
                    art:    true
                    type:   'stats'
                    stages: ['model', 'estimate', 'contrast_manager', 'results']
    paradigms:
        -
            name:   Sent
            n_runs: 6
            n_volumes: 165
            output_directory: /Users/scottburns/Analysis/LDRC_KKI/
            data_toplevel: /Volumes/Data/LDRC_KKI/
            run_directory:
                - Sent_M1
                - Sent_M2
                - Sent_M3
                - Sent_M4
                - Sent_M5
                - Sent_M6
            images:
                - SentM1.nii
                - SentM2.nii
                - SentM3.nii
                - SentM4.nii
                - SentM5.nii
                - SentM6.nii
            SPM:
                session:
                    multiple_condition_mat:
                        post-model1:
                            - /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/model1/m1_p1.mat
                            - /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/model1/m2_p1.mat
                            - /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/model1/m3_p1.mat
                            - /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/model1/m4_p1.mat
                            - /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/model1/m5_p1.mat
                            - /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/model1/m6_p1.mat
                        post-model2:
                            - /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/model2/m1_p1.mat
                            - /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/model2/m2_p1.mat
                            - /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/model2/m3_p1.mat
                            - /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/model2/m4_p1.mat
                            - /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/model2/m5_p1.mat
                            - /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/model2/m6_p1.mat                        
            contrasts:
                post-model1:
                    -
                        name:   Meaningful_Sent
                        vector: '1 0 0 0'
                        replication: replsc
                    -
                        name:   Syntactic_Sent
                        vector: '0 1 0 0'
                        replication: replsc
                    -
                        name:   Semantic_Sent
                        vector: '0 0 1 0'
                        replication: replsc
                    -
                        name:   Words
                        vector: '0 0 0 1'
                        replication: replsc
                    -
                        name:   Meaningful-Syntactic
                        vector: '1 -1 0 0'
                        replication: replsc                                 
                    -
                        name:   Syntactic-Meaningful
                        vector: '-1 1 0 0'
                        replication: replsc
                    -
                        name:   Meaningful-Semantic
                        vector: '1 0 -1 0'
                        replication: replsc
                    -
                        name:   Semantic-Meaningful
                        vector: '-1 0 1 0'
                        replication: replsc
                    -
                        name:   Meaningful-Words
                        vector: '1 0 0 -1'
                        replication: replsc
                    -
                        name:   Words-Meaningful
                        vector: '-1 0 0 1'
                        replication: replsc
                    -
                        name:   Semantic-Words
                        vector: '0 0 1 -1'
                        replication: replsc
                    -
                        name:   Words-Semantic
                        vector: '0 0 -1 1'
                        replication: replsc
                    -
                        name:   Syntactic-Words
                        vector: '0 1 0 -1'
                        replication: replsc
                    -
                        name:   Words-Syntactic
                        vector: '0 -1 0 1'
                        replication: replsc
                    -
                        name:   Syntactic-Semantic
                        vector: '0 1 -1 0'
                        replication: replsc
                    -
                        name:   Semantic-Syntactic
                        vector: '0 -1 1 0'
                        replication: replsc
                post-model2:
                    -
                        name:   TrueSent-3
                        vector: '1 0 0 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   NonSent-3
                        vector: '0 1 0 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   Words-3
                        vector: '0 0 1 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   True3-Non3
                        vector: '1 -1 0 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   Non3-True3
                        vector: '-1 1 0 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   True3-Words3
                        vector: '1 0 -1 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   Words3-True3
                        vector: '-1 0 1 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   Non3-Words3
                        vector: '0 1 -1 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   Words3-Non3
                        vector: '0 -1 1 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   TrueSent-5
                        vector: '0 0 1 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   NonSent-5
                        vector: '0 0 0 1 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   Words-5
                        vector: '0 0 0 0 1 0 0 0 0'
                        replication: replsc
                    -
                        name:   True5-Non5
                        vector: '0 0 0 1 -1 0 0 0 0'
                        replication: replsc
                    -
                        name:   Non5-True5
                        vector: '0 0 0 -1 1 0 0 0 0'
                        replication: replsc
                    -
                        name:   True5-Words5
                        vector: '0 0 0 1 0 -1 0 0 0'
                        replication: replsc
                    -
                        name:   Words5-True5
                        vector: '0 0 0 -1 0 1 0 0 0'
                        replication: replsc
                    -
                        name:   Non5-Words5
                        vector: '0 0 0 0 1 -1 0 0 0'
                        replication: replsc
                    -
                        name:   Words5-Non5
                        vector: '0 0 0 0 -1 1 0 0 0'
                        replication: replsc
                    -
                        name:   TrueSent-7
                        vector: '0 0 0 0 0 1 0 0 0'
                        replication: replsc
                    -
                        name:   NonSent-7
                        vector: '0 0 0 0 0 0 0 1 0'
                        replication: replsc
                    -
                        name:   Words-7
                        vector: '0 0 0 0 0 0 0 0 1'
                        replication: replsc
                    -
                        name:   True7-Non7
                        vector: '0 0 0 0 0 0 1 -1 0'
                        replication: replsc
                    -
                        name:   Non7-True7
                        vector: ' 0 0 0 0 0 0 -1 1 0'
                        replication: replsc
                    -
                        name:   True7-Words7
                        vector: '0 0 0 0 0 0 1 0 -1'
                        replication: replsc
                    -
                        name:   Words7-True7
                        vector: '0 0 0 0 0 0 -1 0 1'
                        replication: replsc
                    -
                        name:   Non7-Words7
                        vector: '0 0 0 0 0 0 0 1 -1'
                        replication: replsc
                    -
                        name:   Words7-Non7
                        vector: '0 0 0 0 0 0 0 -1 1'
                        replication: replsc
                    -
                        name:   True3-True5
                        vector: '0 0 0 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   True3-True5
                        vector: '0 0 0 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   True3-True5
                        vector: '0 0 0 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   True3-True5
                        vector: '0 0 0 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   True3-True5
                        vector: '0 0 0 0 0 0 0 0 0'
                        replication: replsc
                    -
                        name:   True3-True5
                        vector: '0 0 0 0 0 0 0 0 0'
                        replication: replsc
        
