subjects:
- {id: LDRC_71001
   grp: 
   grp: }
- {id: LDRC_71002
   grp: }
- {id: LDRC_71004
   grp: }
- {id: LDRC_71005
   grp: }
- {id: LDRC_71006
   grp: }
- {id: LDRC_71009
   grp: }
- {id: LDRC_71010
   grp: }
- {id: LDRC_71013
   grp: }
- {id: LDRC_71015
   grp: }
- {id: LDRC_71016
   grp: }
- {id: LDRC_71017
   grp: }
- {id: LDRC_71018
   grp: }
- {id: LDRC_71019
   grp: }
- {id: LDRC_71020
   grp: }
- {id: LDRC_71021
   grp: }
- {id: LDRC_71022
   grp: }
- {id: LDRC_71025
   grp: }
- {id: LDRC_71026
   grp: }
- {id: LDRC_71028
   grp: }
- {id: LDRC_71031
   grp: }
- {id: LDRC_71032
   grp: }
- {id: LDRC_71033
   grp: }
- {id: LDRC_71035
   grp: }
- {id: LDRC_71036
   grp: }
- {id: LDRC_71038
   grp: }
- {id: LDRC_71039
   grp: }
- {id: LDRC_71040
   grp: }
- {id: LDRC_71041
   grp: }
- {id: LDRC_71044
   grp: }
- {id: LDRC_71046
   grp: }
- {id: LDRC_71048
   grp: }
- {id: LDRC_71049
   grp: }
- {id: LDRC_71050
   grp: }
- {id: LDRC_71053
   grp: }
- {id: LDRC_71054
   grp: }
- {id: LDRC_71061
   grp: }
- {id: LDRC_71062
   grp: }
- {id: LDRC_71063
   grp: }
- {id: LDRC_71064
   grp: }
- {id: LDRC_71065
   grp: }
- {id: LDRC_71066
   grp: }
- {id: LDRC_71070
   grp: }
- {id: LDRC_71071
   grp: }
- {id: LDRC_71073
   grp: }
- {id: LDRC_71075
   grp: }
- {id: LDRC_71077
   grp: }
- {id: LDRC_71078
   grp: }
- {id: LDRC_71080
   grp: }
- {id: LDRC_71081
   grp: }
- {id: LDRC_71082
   grp: }
- {id: LDRC_71083
   grp: }
- {id: LDRC_71084
   grp: }
- {id: LDRC_71085
   grp: }
- {id: LDRC_71086
   grp: }
- {id: LDRC_71087
   grp: }
- {id: LDRC_71088
   grp: }
- {id: LDRC_71090
   grp: }
- {id: LDRC_71092
   grp: }
- {id: LDRC_71093
   grp: }
- {id: LDRC_71094
   grp: }
- {id: LDRC_71096
   grp: }
- {id: LDRC_71097
   grp: }
- {id: LDRC_71098
   grp: }
- {id: LDRC_71099
   grp: }
- {id: LDRC_71100
   grp: }
- {id: LDRC_71105
   grp: }
- {id: LDRC_71106
   grp: }
- {id: LDRC_71110
   grp: }
- {id: LDRC_71111
   grp: }
- {id: LDRC_71112
   grp: }
- {id: LDRC_71113
   grp: }
- {id: LDRC_71114
   grp: }
- {id: LDRC_71115
   grp: }
- {id: LDRC_71116
   grp: }
- {id: LDRC_71117
   grp: }
- {id: LDRC_71118
   grp: }
- {id: LDRC_71119
   grp: }
- {id: LDRC_71120
   grp: }
- {id: LDRC_71121
   grp: }
- {id: LDRC_71122
   grp: }
- {id: LDRC_71125
   grp: }
- {id: LDRC_71126
   grp: }
- {id: LDRC_71127
   grp: }
- {id: LDRC_71128
   grp: }
- {id: LDRC_71129
   grp: }
- {id: LDRC_71131
   grp: }
- {id: LDRC_71132
   grp: }
- {id: LDRC_71133
   grp: }
- {id: LDRC_71135
   grp: }
version: 1
