subjects:
- {id: LDRC_71001, grp: CNT}
- {id: LDRC_71002, grp: GRD}
- {id: LDRC_71004, grp: CNT}
- {id: LDRC_71005, grp: CNT}
- {id: LDRC_71006, grp: CNT}
#- {id: LDRC_71009, grp: RCD}
#- {id: LDRC_71010, grp: CNT}
#- {id: LDRC_71013, grp: WRD}
- {id: LDRC_71015, grp: GRD}
#- {id: LDRC_71016, grp: RCD}
#- {id: LDRC_71017, grp: RCD}
- {id: LDRC_71018, grp: GRD}
- {id: LDRC_71019, grp: GRD}
- {id: LDRC_71020, grp: GRD}
- {id: LDRC_71021, grp: CNT}
- {id: LDRC_71022, grp: CNT}
#- {id: LDRC_71025, grp: CNT}
- {id: LDRC_71026, grp: GRD}
#- {id: LDRC_71028, grp: AMBIG}
- {id: LDRC_71031, grp: CNT}
#- {id: LDRC_71032, grp: GRD}
#- {id: LDRC_71033, grp: CNT}
- {id: LDRC_71035, grp: GRD}
#- {id: LDRC_71036, grp: WRD}
#- {id: LDRC_71038, grp: AMBIG}
#- {id: LDRC_71039, grp: AMBIG}
#- {id: LDRC_71040, grp: RCD}
- {id: LDRC_71041, grp: CNT}
#- {id: LDRC_71044, grp: AMBIG}
- {id: LDRC_71046, grp: CNT}
#- {id: LDRC_71048, grp: RCD}
#- {id: LDRC_71049, grp: AMBIG} 
- {id: LDRC_71050, grp: CNT}
#- {id: LDRC_71053, grp: RCD}
#- {id: LDRC_71054, grp: AMBIG}
- {id: LDRC_71061, grp: AMBIG}
- {id: LDRC_71062, grp: CNT}
- {id: LDRC_71063, grp: CNT}
#- {id: LDRC_71064, grp: RCD}
- {id: LDRC_71065, grp: AMBIG}
#- {id: LDRC_71066, grp: RCD}
#- {id: LDRC_71070, grp: RCD}
#- {id: LDRC_71071, grp: GRD}
#- {id: LDRC_71073, grp: CNT}
#- {id: LDRC_71075, grp: RCD}
- {id: LDRC_71077, grp: GRD}
- {id: LDRC_71078, grp: GRD}
- {id: LDRC_71080, grp: GRD}
- {id: LDRC_71081, grp: GRD}
- {id: LDRC_71082, grp: CNT}
- {id: LDRC_71083, grp: CNT}
- {id: LDRC_71084, grp: CNT}
#- {id: LDRC_71085, grp: RCD}
#- {id: LDRC_71086, grp: AMBIG}
- {id: LDRC_71087, grp: CNT}
- {id: LDRC_71088, grp: CNT}
#- {id: LDRC_71090, grp: AMBIG}
- {id: LDRC_71092, grp: GRD}
- {id: LDRC_71093, grp: GRD}
- {id: LDRC_71094, grp: GRD}
- {id: LDRC_71096, grp: GRD}
#- {id: LDRC_71097, grp: RCD}
- {id: LDRC_71098, grp: CNT}
- {id: LDRC_71099, grp: CNT}
- {id: LDRC_71100, grp: GRD}
#- {id: LDRC_71105, grp: RCD}
#- {id: LDRC_71106, grp: RCD}
#- {id: LDRC_71110, grp: GRD}
- {id: LDRC_71111, grp: GRD}
- {id: LDRC_71112, grp: GRD}
- {id: LDRC_71113, grp: CNT}
- {id: LDRC_71114, grp: GRD}
#- {id: LDRC_71115, grp: RCD}
- {id: LDRC_71116, grp: CNT}
- {id: LDRC_71117, grp: GRD}
#- {id: LDRC_71118, grp: CNT}
#- {id: LDRC_71119, grp: RCD}
#- {id: LDRC_71120, grp: AMBIG}
#- {id: LDRC_71121, grp: GRD}
#- {id: LDRC_71122, grp: CNT}
#- {id: LDRC_71125, grp: CNT}
#- {id: LDRC_71126, grp: CNT}
#- {id: LDRC_71127, grp: CNT}
#- {id: LDRC_71128, grp: GRD}
#- {id: LDRC_71129, grp: CNT}
#- {id: LDRC_71131, grp: NA}
#- {id: LDRC_71132, grp: NA}
#- {id: LDRC_71133, grp: NA}
#- {id: LDRC_71135, grp: NA}
version: 1
