SPM:
  contrast: {batch_n: 3}
  contrast_manager: {batch_n: 3, contrast: gen, delete: 1, spm_mat_file: gen}
  estimate: {batch_n: 2, spm_mat_file: gen}
  model: {TR: 2.2, batch_n: 1, directory: gen, explicit_mask: '', global_normalization: None,
    hrf_derivatives: 0 0, microtime_onset: 1, microtime_resolution: 16, serial_correlations: AR(1),
    session: gen, timing_units: scans, volterra_interactions: 1}
  normalize-er: {batch_n: 3, bounding_box: -78 -112 -50; 78 76 85, freq_cutoff: 25,
    images: gen, interpolation: 2, iterations: 16, prefix: w, preserve: 0, reg_type: mni,
    regularization: 1, source: gen, source_smooth: 6, template: '/Applications/spm8/templates/EPI.nii,1',
    template_smooth: 0, template_weight: '', voxel_size: 2 2 2, weight_src: '', wrap: 0
      0 0}
  realign-er: {batch_n: 2, e_interpolation: 2, e_wrap: 0 0 0, images: gen, mask: 1,
    num_passes: 0, prefix: r, quality: 1.0, r_interpolation: 4, r_wrap: 0 0 0, separation: 4,
    smoothing: 6, weight: '', which: 2 1}
  results: {batch_n: 4, contrasts: Inf, spm_mat_file: gen, thresh_desc: none, threshold: 0.05,
    titlestr: ''}
  session: {batch_n: 1, hpf: 128, images: gen, multiple_condition_mat: gen, multiple_regression_file: gen,
    session_n: gen}
  slicetime: {batch_n: 1, images: gen, nslices: 40, prefix: a, ref: 20, so: 1 2 3
      4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
      32 33 34 35 36 37 38 39 40, ta: 2.145, tr: 2.2}
  smooth: {batch_n: 4, datatype: 0, fwhm: 8 8 8, images: gen, implicit: 0, prefix: s}
  spec: 1
project:
  name: LDRC_KKI
  paradigms:
  - SPM:
      session:
        multiple_condition_mat: [/Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/m1_p1.mat,
          /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/m2_p1.mat, /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/m3_p1.mat,
          /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/m4_p1.mat, /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/m5_p1.mat,
          /Users/scottburns/Analysis/LDRC_KKI/Sent/mult_cond/m6_p1.mat]
    contrasts:
    - {name: TrueSent-3, replication: replsc, vector: 1 0 0 0 0 0 0 0 0}
    - {name: NonSent-3, replication: replsc, vector: 0 1 0 0 0 0 0 0 0}
    - {name: Words-3, replication: replsc, vector: 0 0 1 0 0 0 0 0 0}
    - {name: TrueSent-5, replication: replsc, vector: 0 0 1 0 0 0 0 0 0}
    - {name: NonSent-5, replication: replsc, vector: 0 0 0 1 0 0 0 0 0}
    - {name: Words-5, replication: replsc, vector: 0 0 0 0 1 0 0 0 0}
    - {name: TrueSent-7, replication: replsc, vector: 0 0 0 0 0 1 0 0 0}
    - {name: NonSent-7, replication: replsc, vector: 0 0 0 0 0 0 0 1 0}
    - {name: Words-7, replication: replsc, vector: 0 0 0 0 0 0 0 0 1}
    n_runs: 6
    n_volumes: 165
    name: Sent
    output_directory: /Users/scottburns/Analysis/LDRC_KKI/
  spec: 1
  todo:
    SPM:
      post: [model, estimate, contrast_manager, results]
      pre: [slicetime, realign-er, normalize-er, smooth]
subjects:
- Sent:
    images: [/Users/scottburns/Data/LDRC_KKI/LDRC_71002/P1_71002_3_1/P1_71002_3_1.nii,
      /Users/scottburns/Data/LDRC_KKI/LDRC_71002/P1_71002_4_1/P1_71002_4_1.nii, /Users/scottburns/Data/LDRC_KKI/LDRC_71002/P1_71002_5_1/P1_71002_5_1.nii,
      /Users/scottburns/Data/LDRC_KKI/LDRC_71002/P1_71002_6_1/P1_71002_6_1.nii, /Users/scottburns/Data/LDRC_KKI/LDRC_71002/P1_71002_7_1/P1_71002_7_1.nii,
      /Users/scottburns/Data/LDRC_KKI/LDRC_71002/P1_71002_8_1/P1_71002_8_1.nii]
  id: LDRC_71002
- Sent:
    images: [/Users/scottburns/Data/LDRC_KKI/LDRC_71009/P1_71009_19_1/P1_71009_19_1.nii,
      /Users/scottburns/Data/LDRC_KKI/LDRC_71009/P1_71009_21_1/P1_71009_21_1.nii,
      /Users/scottburns/Data/LDRC_KKI/LDRC_71009/P1_71009_22_1/P1_71009_22_1.nii,
      /Users/scottburns/Data/LDRC_KKI/LDRC_71009/P1_71009_26_1/P1_71009_26_1.nii,
      /Users/scottburns/Data/LDRC_KKI/LDRC_71009/P1_71009_27_1/P1_71009_27_1.nii,
      /Users/scottburns/Data/LDRC_KKI/LDRC_71009/P1_71009_30_1/P1_71009_30_1.nii]
  id: LDRC_71009
- Sent:
    images: [/Users/scottburns/Data/LDRC_KKI/LDRC_71001/P1_71001_16_1/P1_71001_16_1.nii,
      /Users/scottburns/Data/LDRC_KKI/LDRC_71001/P1_71001_17_1/P1_71001_17_1.nii,
      /Users/scottburns/Data/LDRC_KKI/LDRC_71001/P1_71001_18_1/P1_71001_18_1.nii]
    n_runs: 3
  id: LDRC_71001
version: 1
